; Auto-generated. Do not edit!


(cl:in-package alpheus_actions-msg)


;//! \htmlinclude depthGoal.msg.html

(cl:defclass <depthGoal> (roslisp-msg-protocol:ros-message)
  ((depth_setpoint
    :reader depth_setpoint
    :initarg :depth_setpoint
    :type cl:float
    :initform 0.0))
)

(cl:defclass depthGoal (<depthGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <depthGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'depthGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name alpheus_actions-msg:<depthGoal> is deprecated: use alpheus_actions-msg:depthGoal instead.")))

(cl:ensure-generic-function 'depth_setpoint-val :lambda-list '(m))
(cl:defmethod depth_setpoint-val ((m <depthGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader alpheus_actions-msg:depth_setpoint-val is deprecated.  Use alpheus_actions-msg:depth_setpoint instead.")
  (depth_setpoint m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <depthGoal>) ostream)
  "Serializes a message object of type '<depthGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'depth_setpoint))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <depthGoal>) istream)
  "Deserializes a message object of type '<depthGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'depth_setpoint) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<depthGoal>)))
  "Returns string type for a message object of type '<depthGoal>"
  "alpheus_actions/depthGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'depthGoal)))
  "Returns string type for a message object of type 'depthGoal"
  "alpheus_actions/depthGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<depthGoal>)))
  "Returns md5sum for a message object of type '<depthGoal>"
  "eac9b1c2b936598b47862f11c21394fc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'depthGoal)))
  "Returns md5sum for a message object of type 'depthGoal"
  "eac9b1c2b936598b47862f11c21394fc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<depthGoal>)))
  "Returns full string definition for message of type '<depthGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 depth_setpoint~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'depthGoal)))
  "Returns full string definition for message of type 'depthGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 depth_setpoint~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <depthGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <depthGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'depthGoal
    (cl:cons ':depth_setpoint (depth_setpoint msg))
))
