; Auto-generated. Do not edit!


(cl:in-package alpheus_actions-msg)


;//! \htmlinclude depthResult.msg.html

(cl:defclass <depthResult> (roslisp-msg-protocol:ros-message)
  ((depth_final
    :reader depth_final
    :initarg :depth_final
    :type cl:float
    :initform 0.0))
)

(cl:defclass depthResult (<depthResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <depthResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'depthResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name alpheus_actions-msg:<depthResult> is deprecated: use alpheus_actions-msg:depthResult instead.")))

(cl:ensure-generic-function 'depth_final-val :lambda-list '(m))
(cl:defmethod depth_final-val ((m <depthResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader alpheus_actions-msg:depth_final-val is deprecated.  Use alpheus_actions-msg:depth_final instead.")
  (depth_final m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <depthResult>) ostream)
  "Serializes a message object of type '<depthResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'depth_final))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <depthResult>) istream)
  "Deserializes a message object of type '<depthResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'depth_final) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<depthResult>)))
  "Returns string type for a message object of type '<depthResult>"
  "alpheus_actions/depthResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'depthResult)))
  "Returns string type for a message object of type 'depthResult"
  "alpheus_actions/depthResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<depthResult>)))
  "Returns md5sum for a message object of type '<depthResult>"
  "efffe5edefe0c91e677badcefaef96f3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'depthResult)))
  "Returns md5sum for a message object of type 'depthResult"
  "efffe5edefe0c91e677badcefaef96f3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<depthResult>)))
  "Returns full string definition for message of type '<depthResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32 depth_final~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'depthResult)))
  "Returns full string definition for message of type 'depthResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32 depth_final~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <depthResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <depthResult>))
  "Converts a ROS message object to a list"
  (cl:list 'depthResult
    (cl:cons ':depth_final (depth_final msg))
))
