; Auto-generated. Do not edit!


(cl:in-package alpheus_actions-msg)


;//! \htmlinclude depthFeedback.msg.html

(cl:defclass <depthFeedback> (roslisp-msg-protocol:ros-message)
  ((depth_error
    :reader depth_error
    :initarg :depth_error
    :type cl:float
    :initform 0.0))
)

(cl:defclass depthFeedback (<depthFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <depthFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'depthFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name alpheus_actions-msg:<depthFeedback> is deprecated: use alpheus_actions-msg:depthFeedback instead.")))

(cl:ensure-generic-function 'depth_error-val :lambda-list '(m))
(cl:defmethod depth_error-val ((m <depthFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader alpheus_actions-msg:depth_error-val is deprecated.  Use alpheus_actions-msg:depth_error instead.")
  (depth_error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <depthFeedback>) ostream)
  "Serializes a message object of type '<depthFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'depth_error))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <depthFeedback>) istream)
  "Deserializes a message object of type '<depthFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'depth_error) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<depthFeedback>)))
  "Returns string type for a message object of type '<depthFeedback>"
  "alpheus_actions/depthFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'depthFeedback)))
  "Returns string type for a message object of type 'depthFeedback"
  "alpheus_actions/depthFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<depthFeedback>)))
  "Returns md5sum for a message object of type '<depthFeedback>"
  "a6235a4a90ad5af2d84511b2165d37c8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'depthFeedback)))
  "Returns md5sum for a message object of type 'depthFeedback"
  "a6235a4a90ad5af2d84511b2165d37c8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<depthFeedback>)))
  "Returns full string definition for message of type '<depthFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 depth_error~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'depthFeedback)))
  "Returns full string definition for message of type 'depthFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 depth_error~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <depthFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <depthFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'depthFeedback
    (cl:cons ':depth_error (depth_error msg))
))
