; Auto-generated. Do not edit!


(cl:in-package alpheus_actions-msg)


;//! \htmlinclude headingResult.msg.html

(cl:defclass <headingResult> (roslisp-msg-protocol:ros-message)
  ((heading_final
    :reader heading_final
    :initarg :heading_final
    :type cl:float
    :initform 0.0))
)

(cl:defclass headingResult (<headingResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <headingResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'headingResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name alpheus_actions-msg:<headingResult> is deprecated: use alpheus_actions-msg:headingResult instead.")))

(cl:ensure-generic-function 'heading_final-val :lambda-list '(m))
(cl:defmethod heading_final-val ((m <headingResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader alpheus_actions-msg:heading_final-val is deprecated.  Use alpheus_actions-msg:heading_final instead.")
  (heading_final m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <headingResult>) ostream)
  "Serializes a message object of type '<headingResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'heading_final))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <headingResult>) istream)
  "Deserializes a message object of type '<headingResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'heading_final) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<headingResult>)))
  "Returns string type for a message object of type '<headingResult>"
  "alpheus_actions/headingResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'headingResult)))
  "Returns string type for a message object of type 'headingResult"
  "alpheus_actions/headingResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<headingResult>)))
  "Returns md5sum for a message object of type '<headingResult>"
  "472db86d44a55f5ad3f81a4863ee07f6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'headingResult)))
  "Returns md5sum for a message object of type 'headingResult"
  "472db86d44a55f5ad3f81a4863ee07f6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<headingResult>)))
  "Returns full string definition for message of type '<headingResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32 heading_final~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'headingResult)))
  "Returns full string definition for message of type 'headingResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32 heading_final~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <headingResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <headingResult>))
  "Converts a ROS message object to a list"
  (cl:list 'headingResult
    (cl:cons ':heading_final (heading_final msg))
))
