; Auto-generated. Do not edit!


(cl:in-package alpheus_actions-msg)


;//! \htmlinclude headingGoal.msg.html

(cl:defclass <headingGoal> (roslisp-msg-protocol:ros-message)
  ((heading_setpoint
    :reader heading_setpoint
    :initarg :heading_setpoint
    :type cl:float
    :initform 0.0))
)

(cl:defclass headingGoal (<headingGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <headingGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'headingGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name alpheus_actions-msg:<headingGoal> is deprecated: use alpheus_actions-msg:headingGoal instead.")))

(cl:ensure-generic-function 'heading_setpoint-val :lambda-list '(m))
(cl:defmethod heading_setpoint-val ((m <headingGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader alpheus_actions-msg:heading_setpoint-val is deprecated.  Use alpheus_actions-msg:heading_setpoint instead.")
  (heading_setpoint m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <headingGoal>) ostream)
  "Serializes a message object of type '<headingGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'heading_setpoint))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <headingGoal>) istream)
  "Deserializes a message object of type '<headingGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'heading_setpoint) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<headingGoal>)))
  "Returns string type for a message object of type '<headingGoal>"
  "alpheus_actions/headingGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'headingGoal)))
  "Returns string type for a message object of type 'headingGoal"
  "alpheus_actions/headingGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<headingGoal>)))
  "Returns md5sum for a message object of type '<headingGoal>"
  "92b7d9ffbfb88af138a218b11bdf7a0a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'headingGoal)))
  "Returns md5sum for a message object of type 'headingGoal"
  "92b7d9ffbfb88af138a218b11bdf7a0a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<headingGoal>)))
  "Returns full string definition for message of type '<headingGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 heading_setpoint~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'headingGoal)))
  "Returns full string definition for message of type 'headingGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 heading_setpoint~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <headingGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <headingGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'headingGoal
    (cl:cons ':heading_setpoint (heading_setpoint msg))
))
