; Auto-generated. Do not edit!


(cl:in-package alpheus_actions-msg)


;//! \htmlinclude headingFeedback.msg.html

(cl:defclass <headingFeedback> (roslisp-msg-protocol:ros-message)
  ((heading_error
    :reader heading_error
    :initarg :heading_error
    :type cl:float
    :initform 0.0))
)

(cl:defclass headingFeedback (<headingFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <headingFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'headingFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name alpheus_actions-msg:<headingFeedback> is deprecated: use alpheus_actions-msg:headingFeedback instead.")))

(cl:ensure-generic-function 'heading_error-val :lambda-list '(m))
(cl:defmethod heading_error-val ((m <headingFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader alpheus_actions-msg:heading_error-val is deprecated.  Use alpheus_actions-msg:heading_error instead.")
  (heading_error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <headingFeedback>) ostream)
  "Serializes a message object of type '<headingFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'heading_error))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <headingFeedback>) istream)
  "Deserializes a message object of type '<headingFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'heading_error) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<headingFeedback>)))
  "Returns string type for a message object of type '<headingFeedback>"
  "alpheus_actions/headingFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'headingFeedback)))
  "Returns string type for a message object of type 'headingFeedback"
  "alpheus_actions/headingFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<headingFeedback>)))
  "Returns md5sum for a message object of type '<headingFeedback>"
  "5f1b6285c1393230e9f909df240d5f12")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'headingFeedback)))
  "Returns md5sum for a message object of type 'headingFeedback"
  "5f1b6285c1393230e9f909df240d5f12")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<headingFeedback>)))
  "Returns full string definition for message of type '<headingFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 heading_error~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'headingFeedback)))
  "Returns full string definition for message of type 'headingFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 heading_error~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <headingFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <headingFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'headingFeedback
    (cl:cons ':heading_error (heading_error msg))
))
