// Generated by gencpp from file alpheus_actions/headingGoal.msg
// DO NOT EDIT!


#ifndef ALPHEUS_ACTIONS_MESSAGE_HEADINGGOAL_H
#define ALPHEUS_ACTIONS_MESSAGE_HEADINGGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alpheus_actions
{
template <class ContainerAllocator>
struct headingGoal_
{
  typedef headingGoal_<ContainerAllocator> Type;

  headingGoal_()
    : heading_setpoint(0.0)  {
    }
  headingGoal_(const ContainerAllocator& _alloc)
    : heading_setpoint(0.0)  {
  (void)_alloc;
    }



   typedef float _heading_setpoint_type;
  _heading_setpoint_type heading_setpoint;




  typedef boost::shared_ptr< ::alpheus_actions::headingGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alpheus_actions::headingGoal_<ContainerAllocator> const> ConstPtr;

}; // struct headingGoal_

typedef ::alpheus_actions::headingGoal_<std::allocator<void> > headingGoal;

typedef boost::shared_ptr< ::alpheus_actions::headingGoal > headingGoalPtr;
typedef boost::shared_ptr< ::alpheus_actions::headingGoal const> headingGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alpheus_actions::headingGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alpheus_actions::headingGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alpheus_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'alpheus_msgs': ['/home/pushkalkatara/Desktop/PUbuntu/AUV/alpheus/src/alpheus_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'alpheus_actions': ['/home/pushkalkatara/Desktop/PUbuntu/AUV/alpheus/devel/share/alpheus_actions/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alpheus_actions::headingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alpheus_actions::headingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alpheus_actions::headingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alpheus_actions::headingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alpheus_actions::headingGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alpheus_actions::headingGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alpheus_actions::headingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92b7d9ffbfb88af138a218b11bdf7a0a";
  }

  static const char* value(const ::alpheus_actions::headingGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92b7d9ffbfb88af1ULL;
  static const uint64_t static_value2 = 0x38a218b11bdf7a0aULL;
};

template<class ContainerAllocator>
struct DataType< ::alpheus_actions::headingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alpheus_actions/headingGoal";
  }

  static const char* value(const ::alpheus_actions::headingGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alpheus_actions::headingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
float32 heading_setpoint\n\
";
  }

  static const char* value(const ::alpheus_actions::headingGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alpheus_actions::headingGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading_setpoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct headingGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alpheus_actions::headingGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alpheus_actions::headingGoal_<ContainerAllocator>& v)
  {
    s << indent << "heading_setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.heading_setpoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALPHEUS_ACTIONS_MESSAGE_HEADINGGOAL_H
