// Generated by gencpp from file alpheus_msgs/headingPID.msg
// DO NOT EDIT!


#ifndef ALPHEUS_MSGS_MESSAGE_HEADINGPID_H
#define ALPHEUS_MSGS_MESSAGE_HEADINGPID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alpheus_msgs
{
template <class ContainerAllocator>
struct headingPID_
{
  typedef headingPID_<ContainerAllocator> Type;

  headingPID_()
    : hKp(0.0)
    , hKi(0.0)
    , hKd(0.0)  {
    }
  headingPID_(const ContainerAllocator& _alloc)
    : hKp(0.0)
    , hKi(0.0)
    , hKd(0.0)  {
  (void)_alloc;
    }



   typedef float _hKp_type;
  _hKp_type hKp;

   typedef float _hKi_type;
  _hKi_type hKi;

   typedef float _hKd_type;
  _hKd_type hKd;




  typedef boost::shared_ptr< ::alpheus_msgs::headingPID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alpheus_msgs::headingPID_<ContainerAllocator> const> ConstPtr;

}; // struct headingPID_

typedef ::alpheus_msgs::headingPID_<std::allocator<void> > headingPID;

typedef boost::shared_ptr< ::alpheus_msgs::headingPID > headingPIDPtr;
typedef boost::shared_ptr< ::alpheus_msgs::headingPID const> headingPIDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alpheus_msgs::headingPID_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alpheus_msgs::headingPID_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alpheus_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'alpheus_msgs': ['/home/pushkalkatara/Desktop/PUbuntu/AUV/alpheus/src/alpheus_msgs/msg', '/home/pushkalkatara/Desktop/PUbuntu/AUV/alpheus/src/alpheus_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alpheus_msgs::headingPID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alpheus_msgs::headingPID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alpheus_msgs::headingPID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alpheus_msgs::headingPID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alpheus_msgs::headingPID_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alpheus_msgs::headingPID_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alpheus_msgs::headingPID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19a0fa31de3cf3c925595e656db1566d";
  }

  static const char* value(const ::alpheus_msgs::headingPID_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19a0fa31de3cf3c9ULL;
  static const uint64_t static_value2 = 0x25595e656db1566dULL;
};

template<class ContainerAllocator>
struct DataType< ::alpheus_msgs::headingPID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alpheus_msgs/headingPID";
  }

  static const char* value(const ::alpheus_msgs::headingPID_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alpheus_msgs::headingPID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 hKp\n\
float32 hKi\n\
float32 hKd\n\
";
  }

  static const char* value(const ::alpheus_msgs::headingPID_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alpheus_msgs::headingPID_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hKp);
      stream.next(m.hKi);
      stream.next(m.hKd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct headingPID_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alpheus_msgs::headingPID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alpheus_msgs::headingPID_<ContainerAllocator>& v)
  {
    s << indent << "hKp: ";
    Printer<float>::stream(s, indent + "  ", v.hKp);
    s << indent << "hKi: ";
    Printer<float>::stream(s, indent + "  ", v.hKi);
    s << indent << "hKd: ";
    Printer<float>::stream(s, indent + "  ", v.hKd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALPHEUS_MSGS_MESSAGE_HEADINGPID_H
