// Generated by gencpp from file alpheus_msgs/offsetData.msg
// DO NOT EDIT!


#ifndef ALPHEUS_MSGS_MESSAGE_OFFSETDATA_H
#define ALPHEUS_MSGS_MESSAGE_OFFSETDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alpheus_msgs
{
template <class ContainerAllocator>
struct offsetData_
{
  typedef offsetData_<ContainerAllocator> Type;

  offsetData_()
    : offsetX(0.0)
    , offsetY(0.0)  {
    }
  offsetData_(const ContainerAllocator& _alloc)
    : offsetX(0.0)
    , offsetY(0.0)  {
  (void)_alloc;
    }



   typedef float _offsetX_type;
  _offsetX_type offsetX;

   typedef float _offsetY_type;
  _offsetY_type offsetY;




  typedef boost::shared_ptr< ::alpheus_msgs::offsetData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alpheus_msgs::offsetData_<ContainerAllocator> const> ConstPtr;

}; // struct offsetData_

typedef ::alpheus_msgs::offsetData_<std::allocator<void> > offsetData;

typedef boost::shared_ptr< ::alpheus_msgs::offsetData > offsetDataPtr;
typedef boost::shared_ptr< ::alpheus_msgs::offsetData const> offsetDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alpheus_msgs::offsetData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alpheus_msgs::offsetData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alpheus_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'alpheus_msgs': ['/home/pushkalkatara/Desktop/PUbuntu/AUV/alpheus/src/alpheus_msgs/msg', '/home/pushkalkatara/Desktop/PUbuntu/AUV/alpheus/src/alpheus_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alpheus_msgs::offsetData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alpheus_msgs::offsetData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alpheus_msgs::offsetData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alpheus_msgs::offsetData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alpheus_msgs::offsetData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alpheus_msgs::offsetData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alpheus_msgs::offsetData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "796ae190d97828899df8883bfe807076";
  }

  static const char* value(const ::alpheus_msgs::offsetData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x796ae190d9782889ULL;
  static const uint64_t static_value2 = 0x9df8883bfe807076ULL;
};

template<class ContainerAllocator>
struct DataType< ::alpheus_msgs::offsetData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alpheus_msgs/offsetData";
  }

  static const char* value(const ::alpheus_msgs::offsetData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alpheus_msgs::offsetData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 offsetX\n\
float32 offsetY\n\
";
  }

  static const char* value(const ::alpheus_msgs::offsetData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alpheus_msgs::offsetData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offsetX);
      stream.next(m.offsetY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct offsetData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alpheus_msgs::offsetData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alpheus_msgs::offsetData_<ContainerAllocator>& v)
  {
    s << indent << "offsetX: ";
    Printer<float>::stream(s, indent + "  ", v.offsetX);
    s << indent << "offsetY: ";
    Printer<float>::stream(s, indent + "  ", v.offsetY);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALPHEUS_MSGS_MESSAGE_OFFSETDATA_H
