// Generated by gencpp from file alpheus_msgs/pressure.msg
// DO NOT EDIT!


#ifndef ALPHEUS_MSGS_MESSAGE_PRESSURE_H
#define ALPHEUS_MSGS_MESSAGE_PRESSURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alpheus_msgs
{
template <class ContainerAllocator>
struct pressure_
{
  typedef pressure_<ContainerAllocator> Type;

  pressure_()
    : pressure(0.0)  {
    }
  pressure_(const ContainerAllocator& _alloc)
    : pressure(0.0)  {
  (void)_alloc;
    }



   typedef float _pressure_type;
  _pressure_type pressure;




  typedef boost::shared_ptr< ::alpheus_msgs::pressure_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alpheus_msgs::pressure_<ContainerAllocator> const> ConstPtr;

}; // struct pressure_

typedef ::alpheus_msgs::pressure_<std::allocator<void> > pressure;

typedef boost::shared_ptr< ::alpheus_msgs::pressure > pressurePtr;
typedef boost::shared_ptr< ::alpheus_msgs::pressure const> pressureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alpheus_msgs::pressure_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alpheus_msgs::pressure_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alpheus_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'alpheus_msgs': ['/home/pushkalkatara/Desktop/PUbuntu/AUV/alpheus/src/alpheus_msgs/msg', '/home/pushkalkatara/Desktop/PUbuntu/AUV/alpheus/src/alpheus_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alpheus_msgs::pressure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alpheus_msgs::pressure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alpheus_msgs::pressure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alpheus_msgs::pressure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alpheus_msgs::pressure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alpheus_msgs::pressure_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alpheus_msgs::pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d08eeab8c09d2ba14f8144e3bbf40d21";
  }

  static const char* value(const ::alpheus_msgs::pressure_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd08eeab8c09d2ba1ULL;
  static const uint64_t static_value2 = 0x4f8144e3bbf40d21ULL;
};

template<class ContainerAllocator>
struct DataType< ::alpheus_msgs::pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alpheus_msgs/pressure";
  }

  static const char* value(const ::alpheus_msgs::pressure_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alpheus_msgs::pressure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pressure\n\
";
  }

  static const char* value(const ::alpheus_msgs::pressure_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alpheus_msgs::pressure_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pressure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pressure_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alpheus_msgs::pressure_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alpheus_msgs::pressure_<ContainerAllocator>& v)
  {
    s << indent << "pressure: ";
    Printer<float>::stream(s, indent + "  ", v.pressure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALPHEUS_MSGS_MESSAGE_PRESSURE_H
