// Auto-generated. Do not edit!

// (in-package alpheus_actions.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class depthFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.depth_error = null;
    }
    else {
      if (initObj.hasOwnProperty('depth_error')) {
        this.depth_error = initObj.depth_error
      }
      else {
        this.depth_error = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type depthFeedback
    // Serialize message field [depth_error]
    bufferOffset = _serializer.float32(obj.depth_error, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type depthFeedback
    let len;
    let data = new depthFeedback(null);
    // Deserialize message field [depth_error]
    data.depth_error = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'alpheus_actions/depthFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a6235a4a90ad5af2d84511b2165d37c8';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    float32 depth_error
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new depthFeedback(null);
    if (msg.depth_error !== undefined) {
      resolved.depth_error = msg.depth_error;
    }
    else {
      resolved.depth_error = 0.0
    }

    return resolved;
    }
};

module.exports = depthFeedback;
