// Auto-generated. Do not edit!

// (in-package alpheus_actions.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class depthGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.depth_setpoint = null;
    }
    else {
      if (initObj.hasOwnProperty('depth_setpoint')) {
        this.depth_setpoint = initObj.depth_setpoint
      }
      else {
        this.depth_setpoint = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type depthGoal
    // Serialize message field [depth_setpoint]
    bufferOffset = _serializer.float32(obj.depth_setpoint, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type depthGoal
    let len;
    let data = new depthGoal(null);
    // Deserialize message field [depth_setpoint]
    data.depth_setpoint = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'alpheus_actions/depthGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'eac9b1c2b936598b47862f11c21394fc';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    float32 depth_setpoint
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new depthGoal(null);
    if (msg.depth_setpoint !== undefined) {
      resolved.depth_setpoint = msg.depth_setpoint;
    }
    else {
      resolved.depth_setpoint = 0.0
    }

    return resolved;
    }
};

module.exports = depthGoal;
