// Auto-generated. Do not edit!

// (in-package alpheus_actions.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class depthResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.depth_final = null;
    }
    else {
      if (initObj.hasOwnProperty('depth_final')) {
        this.depth_final = initObj.depth_final
      }
      else {
        this.depth_final = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type depthResult
    // Serialize message field [depth_final]
    bufferOffset = _serializer.float32(obj.depth_final, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type depthResult
    let len;
    let data = new depthResult(null);
    // Deserialize message field [depth_final]
    data.depth_final = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'alpheus_actions/depthResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'efffe5edefe0c91e677badcefaef96f3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    float32 depth_final
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new depthResult(null);
    if (msg.depth_final !== undefined) {
      resolved.depth_final = msg.depth_final;
    }
    else {
      resolved.depth_final = 0.0
    }

    return resolved;
    }
};

module.exports = depthResult;
