// Auto-generated. Do not edit!

// (in-package alpheus_actions.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class headingResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.heading_final = null;
    }
    else {
      if (initObj.hasOwnProperty('heading_final')) {
        this.heading_final = initObj.heading_final
      }
      else {
        this.heading_final = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type headingResult
    // Serialize message field [heading_final]
    bufferOffset = _serializer.float32(obj.heading_final, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type headingResult
    let len;
    let data = new headingResult(null);
    // Deserialize message field [heading_final]
    data.heading_final = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'alpheus_actions/headingResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '472db86d44a55f5ad3f81a4863ee07f6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    float32 heading_final
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new headingResult(null);
    if (msg.heading_final !== undefined) {
      resolved.heading_final = msg.heading_final;
    }
    else {
      resolved.heading_final = 0.0
    }

    return resolved;
    }
};

module.exports = headingResult;
