// Auto-generated. Do not edit!

// (in-package alpheus_actions.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class headingGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.heading_setpoint = null;
    }
    else {
      if (initObj.hasOwnProperty('heading_setpoint')) {
        this.heading_setpoint = initObj.heading_setpoint
      }
      else {
        this.heading_setpoint = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type headingGoal
    // Serialize message field [heading_setpoint]
    bufferOffset = _serializer.float32(obj.heading_setpoint, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type headingGoal
    let len;
    let data = new headingGoal(null);
    // Deserialize message field [heading_setpoint]
    data.heading_setpoint = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'alpheus_actions/headingGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '92b7d9ffbfb88af138a218b11bdf7a0a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    float32 heading_setpoint
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new headingGoal(null);
    if (msg.heading_setpoint !== undefined) {
      resolved.heading_setpoint = msg.heading_setpoint;
    }
    else {
      resolved.heading_setpoint = 0.0
    }

    return resolved;
    }
};

module.exports = headingGoal;
